name: Update GitHub Stats

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install @octokit/rest
    
    - name: Generate language statistics
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: node scripts/generate-language-stats.js
    
    - name: Generate contribution statistics
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: node scripts/generate-contribution-stats.js
    
    - name: Generate activity graph
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: node scripts/generate-activity-graph.js
    
    - name: Generate streak statistics
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: node scripts/generate-streak-stats.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update language statistics [skip ci]" && git push)